# Generated by Django 4.1 on 2022-12-13 00:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^7\\d{10}$')], verbose_name='Номер телефона')),
                ('code_operator', models.CharField(default='900', max_length=3, verbose_name='Код оператора')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Произвольный тэг')),
                ('tz', models.CharField(blank=True, default='UTC', max_length=100, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала рассылки')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('filter_tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фильтр по тегу')),
                ('filter_codeOperator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фильтр по коду оператора')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения')),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('not sent', 'NOT SENT')], max_length=8, verbose_name='Статус сообщения')),
                ('clientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='mailing.client')),
                ('mailingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail', to='mailing.mailing')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
